### PR TITLE
fix 1.20.70 effect crash

### PR DESCRIPTION
**Pull request by BlusteryS**

### CODE REVIEW

**Comment by BlusteryS** [comment]
another fix was created before my fix

**Comment by tachibana-kanade-angel** [comment]
Test comment

**Review by tachibana-kanade-angel — APPROVED** [review]
AI Review

**Comment by tachibana-kanade-angel** [comment]
AI Review: No blocking issues found. PR fixes MobEffectPacket 1.20.70 crash. Minor: tick field visibility change needs confirmation.

**Pull request closed without merging**
