### PR TITLE
feat: more stairs

### PR DESCRIPTION
**Pull request by KoshakMineDEV**

### CODE REVIEW

**Comment by KoshakMineDEV** [comment]
all this stairs blocks are already in runtime block dumps

**Comment by lt-name** [comment]
runtime_block_states

- [ ] minecraft:cobbled_deepslate_stairs: 440, 448, 465, 471, 486, 503, 527
- [ ] minecraft:polished_deepslate_stairs: 440, 448, 465, 471, 486, 503, 527
- [ ] minecraft:deepslate_tile_stairs: 440, 448, 465, 471, 486, 503, 527
- [ ] minecraft:deepslate_brick_stairs: 440, 448, 465, 471, 486, 503, 527
- [ ] minecraft:mud_brick_stairs: 503, 527, 544, 560, 567, 575, 582, 589, 594, 618, 622

**Comment by KoshakMineDEV** [comment]
> runtime_block_states
> 
> * [ ]  minecraft:cobbled_deepslate_stairs: 440, 448, 465, 471, 486, 503, 527
> * [ ]  minecraft:polished_deepslate_stairs: 440, 448, 465, 471, 486, 503, 527
> * [ ]  minecraft:deepslate_tile_stairs: 440, 448, 465, 471, 486, 503, 527
> * [ ]  minecraft:deepslate_brick_stairs: 440, 448, 465, 471, 486, 503, 527
> * [ ]  minecraft:mud_brick_stairs: 503, 527, 544, 560, 567, 575, 582, 589, 594, 618, 622

they already in it!!

**Comment by lt-name** [comment]
Block names also need to be unified

**Review by lt-name — APPROVED** [review]

**Pull request merged**
