### PR TITLE
Add some blocks

### PR DESCRIPTION
**Pull request by explorer3039**
Some files are from PNX

runtime_block_states:
- [x] CRIMSON_SLAB
- [x] WARPED_SLAB
- [x] CRIMSON_DOUBLE_SLAB
- [x] WARPED_DOUBLE_SLAB
- [x] POLISHED_BLACKSTONE_BRICKS
- [x] POLISHED_BLACKSTONE_BRICK_STAIRS
- [x] BLACKSTONE_STAIRS
- [x] BLACKSTONE_WALL
- [x] POLISHED_BLACKSTONE_BRICK_WALL
- [x] CHISELED_POLISHED_BLACKSTONE
- [x] CRACKED_POLISHED_BLACKSTONE_BRICKS
- [x] GILDED_BLACKSTONE
- [x] BLACKSTONE_SLAB   x419
- [x] BLACKSTONE_DOUBLE_SLAB  x419
- [x] POLISHED_BLACKSTONE_BRICK_SLAB  x419
- [x] POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB x419
- [x] TWISTING_VINES  x419
- [x] POLISHED_BLACKSTONE
- [x] POLISHED_BLACKSTONE_STAIRS x419
- [x] POLISHED_BLACKSTONE_SLAB x419
- [x] POLISHED_BLACKSTONE_DOUBLE_SLAB x419
- [x] POLISHED_BLACKSTONE_PRESSURE_PLATE x419-594
- [x] POLISHED_BLACKSTONE_BUTTON x419-594
- [x] POLISHED_BLACKSTONE_WALL x419-671
- [x] WARPED_HYPHAE x419-685
- [x] CRIMSON_HYPHAE
- [x] STRIPPED_CRIMSON_HYPHAE
- [x] STRIPPED_WARPED_HYPHAE
- [x] CHISELED_NETHER_BRICKS
- [x] CRACKED_NETHER_BRICKS
- [x] QUARTZ_BRICKS

### CODE REVIEW

**Comment by lt-name** [comment]
可以参考[ecnk](https://github.com/EaseCation/Nukkit)给方块加上getColor方法

**Comment by lt-name** [comment]
如果可以的话，加多个方块时尽量拆分开，一次性加太多会导致runtime_block_states修改困难

**Comment by explorer3039** [comment]
> 如果可以的话，加多个方块时尽量拆分开，一次性加太多会导致runtime_block_states修改困难

我一会加

**Comment by explorer3039** [comment]
blockcolor加过了，拆分成小pr有些麻烦，要是实在不行我再拆分

**Pull request merged**
